// app/screens/stats/detail/PermanentDetailScreen.tsx
// =============================================================================
// PERMANENT DETAIL SCREEN
// =============================================================================
//
// Full-screen detail view for a single permanent task template.
// Opened when the user taps a card in the "Permanent Tasks" section of
// StatsScreen. One instance of this screen exists per template card tapped —
// the template's id, name, and color are passed in via `params`.
//
// ── Layout (top to bottom) ────────────────────────────────────────────────────
//
//   DetailHeader          ← blue accent, task name, back arrow
//   CompletionSummaryCard ← ring + total completed + rate %
//   StreakCard            ← current streak + best streak pills
//   TimeRangeCountsCard   ← Week / Month / Year / All Time counts
//   WeekBarGraph          ← 7-bar chart, count/% toggle
//   MonthCalendarGraph    ← current month calendar with fill circles
//   YearOverviewGraph     ← 12-bar Jan–Dec summary
//   DayOfWeekPatternCard  ← all-time totals grouped by weekday (Mon–Sun)
//
// ── Data ─────────────────────────────────────────────────────────────────────
//
//   Currently uses mock data generated by getMockPermanentDetail().
//   When the stats storage layer is ready (Phase 6), replace with:
//     useStats().getPermanentDetailStats(params.id)
//
//   The mock builder intentionally varies output based on the template id
//   so different permanent task cards feel distinct rather than identical.
//
// ── Navigation ────────────────────────────────────────────────────────────────
//
//   Rendered as an overlay screen by MainNavigator (same pattern as
//   CreateTaskScreen). Tab bar is hidden while this screen is visible.
//   Back press calls `onBack`, which clears the overlay and restores tabs.
//
// Props:
//   params  - id, name, and color of the template being shown
//   onBack  - called when the user taps the back arrow in DetailHeader
//
// =============================================================================

import React from 'react';
import { ScrollView, StyleSheet, View } from 'react-native';

// ── Shared detail components ─────────────────────────────────────────────────
import { DetailHeader }          from '../../../components/stats/detail/shared/DetailHeader';
import { CompletionSummaryCard } from '../../../components/stats/detail/shared/CompletionSummaryCard';
import { StreakCard }            from '../../../components/stats/detail/shared/StreakCard';
import { TimeRangeCountsCard }   from '../../../components/stats/detail/shared/TimeRangeCountsCard';
import { WeekBarGraph }          from '../../../components/stats/detail/shared/WeekBarGraph';
import { MonthCalendarGraph, CalendarDayData } from '../../../components/stats/detail/shared/MonthCalendarGraph';
import { YearOverviewGraph, MonthData }        from '../../../components/stats/detail/shared/YearOverviewGraph';
import { DayOfWeekPatternCard, DayOfWeekData } from '../../../components/stats/detail/shared/DayOfWeekPatternCard';

// ── Shared navigation params type ────────────────────────────────────────────
import { StatDetailParams } from '../../../core/types/statDetailTypes';

// ── DayData type (from WeeklyMiniChart — reused by WeekBarGraph) ─────────────
import { DayData } from '../../../components/stats/WeeklyMiniChart';

// =============================================================================
// TYPES
// =============================================================================

interface PermanentDetailScreenProps {
  /** Id, name, and accent color of the template, passed from MainNavigator */
  params: StatDetailParams;
  /** Called when the user presses the back arrow — clears the overlay */
  onBack: () => void;
}

// =============================================================================
// MOCK DATA
// =============================================================================
//
// Replace getMockPermanentDetail() with a real storage call in Phase 6.
//
// The builder accepts the template id so different cards produce meaningfully
// different numbers (avoids every template looking like a clone).
// It hashes the id into a simple offset so values are stable across renders.
//
// Fields produced:
//   completionSummary  → completed + total (for CompletionSummaryCard)
//   streaks            → currentStreak + bestStreak (for StreakCard)
//   rangeCounts        → week/month/year/allTime (for TimeRangeCountsCard)
//   weeklyData         → 7 DayData items Mon–Sun (for WeekBarGraph)
//   monthlyData        → CalendarDayData[] for current month (for MonthCalendarGraph)
//   yearlyData         → 12 MonthData items Jan–Dec (for YearOverviewGraph)
//   dayOfWeekData      → 7 DayOfWeekData items Mon–Sun (for DayOfWeekPatternCard)

interface PermanentDetailMockData {
  completed:       number;
  total:           number;
  currentStreak:   number;
  bestStreak:      number;
  weekCount:       number;
  monthCount:      number;
  yearCount:       number;
  allTimeCount:    number;
  weeklyData:      DayData[];
  monthlyData:     CalendarDayData[];
  yearlyData:      MonthData[];
  dayOfWeekData:   DayOfWeekData[];
}

/**
 * Builds a stable numeric offset (0–9) from a template id string.
 * Used to vary mock values between different template cards.
 */
function idOffset(id: string): number {
  let hash = 0;
  for (let i = 0; i < id.length; i++) hash = (hash + id.charCodeAt(i)) % 10;
  return hash;
}

/** Builds realistic mock detail data for a permanent task template. */
function getMockPermanentDetail(id: string): PermanentDetailMockData {
  const o = idOffset(id); // 0–9

  // ── Completion summary ──────────────────────────────────────────────────────
  const total     = 50 + o * 5;    // 50–95
  const completed = Math.round(total * (0.65 + o * 0.03)); // 65–92%

  // ── Streaks ─────────────────────────────────────────────────────────────────
  const currentStreak = 3 + o;      // 3–12 days
  const bestStreak    = 15 + o * 3; // 15–42 days

  // ── Time range counts ───────────────────────────────────────────────────────
  const weekCount    = 4 + (o % 4);         // 4–7
  const monthCount   = 16 + o * 2;          // 16–34
  const yearCount    = completed;            // same as total completed for a single template
  const allTimeCount = completed;

  // ── Weekly bar chart (Mon–Sun) ──────────────────────────────────────────────
  // For a permanent task, each day is either done (count: 1) or missed (count: 0).
  // total: 1 means the task was scheduled that day; total: 0 means it wasn't.
  // This makes Count mode and % mode genuinely different in WeekBarGraph:
  //   Count mode  → bars proportional to week volume (how many days done)
  //   Percent mode → each bar is 100% (done) or 0% (missed) — shows the pattern
  //
  // Vary which days are missed based on the id offset so different templates look different.
  const weeklyData: DayData[] = [
    { day: 'M', count: 1,              total: 1 },                   // always done Monday
    { day: 'T', count: 1,              total: 1 },                   // always done Tuesday
    { day: 'W', count: o > 4 ? 0 : 1, total: 1 },                   // missed Wed on high-offset templates
    { day: 'T', count: 1,              total: 1 },                   // always done Thursday
    { day: 'F', count: o > 6 ? 0 : 1, total: 1 },                   // missed Fri on very-high-offset templates
    { day: 'S', count: o % 2,          total: 1 },                   // alternates done/missed on Saturday
    { day: 'S', count: 0,              total: 0 },                   // not scheduled Sundays
  ];

  // ── Monthly calendar (current month) ───────────────────────────────────────
  // Generate entries for odd days of the month up to today's date.
  const now          = new Date();
  const todayDate    = now.getDate();
  const monthlyData: CalendarDayData[] = [];

  for (let d = 1; d <= todayDate; d++) {
    // Skip some days to simulate missed completions (pattern: skip every 4th + 7th day)
    const skip = (d + o) % 5 === 0;
    monthlyData.push({
      date:      d,
      completed: skip ? 0 : 1,
      total:     1,
    });
  }

  // ── Yearly bar chart (Jan–Dec) ──────────────────────────────────────────────
  // Template was "created" mid-year — months before the starting month have 0.
  const currentMonth = now.getMonth(); // 0-indexed
  const startMonth   = Math.max(0, currentMonth - 6 - (o % 3)); // started 6–8 months ago

  const yearlyData: MonthData[] = Array.from({ length: 12 }, (_, m) => {
    if (m < startMonth || m > currentMonth) {
      // Before the template existed, or future months
      return { month: m, completed: 0, total: 0 };
    }
    const monthsActive = m - startMonth + 1;
    const base = 10 + (m - startMonth) * 2 + o; // ramps up over time
    return {
      month:     m,
      completed: Math.min(base, 28),
      total:     28,
    };
  });

  // ── Day-of-week pattern (all-time totals by weekday) ────────────────────────
  // `count` = completions ever recorded on this weekday (all history)
  // `total` = times the task was scheduled on this weekday, excluding overdue ones
  //
  // For a permanent task active ~6 months:
  //   Mon–Fri scheduled every week → ~26 occurrences each
  //   Saturday scheduled every other week → ~12 occurrences
  //   Sunday never scheduled → total: 0
  //
  // count is varied by `o` so different templates show different patterns.
  // count is always clamped to total so rates stay ≤ 100%.
  const dayLabels  = ['M', 'T', 'W', 'T', 'F', 'S', 'S'];
  const dayTotals  = [26, 26, 26, 26, 26, 12, 0]; // scheduled occurrences per weekday
  const dayBases   = [24, 22, 20, 18, 21, 8, 0];  // baseline completions (high Mon, drops off)

  const dayOfWeekData: DayOfWeekData[] = dayLabels.map((day, i) => {
    const scheduledTotal = dayTotals[i];
    // Vary completions by id offset — clamped so count never exceeds total
    const rawCount = Math.max(0, dayBases[i] + ((o * (i + 1)) % 5) - 2);
    return {
      day,
      count: Math.min(rawCount, scheduledTotal),
      total: scheduledTotal,
    };
  });

  return {
    completed,
    total,
    currentStreak,
    bestStreak,
    weekCount,
    monthCount,
    yearCount,
    allTimeCount,
    weeklyData,
    monthlyData,
    yearlyData,
    dayOfWeekData,
  };
}

// =============================================================================
// COMPONENT
// =============================================================================

export const PermanentDetailScreen: React.FC<PermanentDetailScreenProps> = ({
  params,
  onBack,
}) => {
  // Build mock data from the template id.
  // Replace this call with a real storage hook when Phase 6 is ready.
  const data = getMockPermanentDetail(params.id);

  const now = new Date();

  return (
    // flex: 1 so the screen fills the overlay container in MainNavigator
    <View style={styles.container}>

      {/* ── Fixed header — not scrollable ───────────────────────────────── */}
      <DetailHeader
        title={params.name}
        color={params.color}
        onBack={onBack}
      />

      {/* ── Scrollable body ─────────────────────────────────────────────── */}
      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >

        {/* 1. Large ring + completed count + rate % */}
        <CompletionSummaryCard
          completed={data.completed}
          total={data.total}
          color={params.color}
        />

        {/* 2. Current streak + best streak */}
        <StreakCard
          currentStreak={data.currentStreak}
          bestStreak={data.bestStreak}
          color={params.color}
        />

        {/* 3. Four-box count summary: Week / Month / Year / All Time */}
        <TimeRangeCountsCard
          weekCount={data.weekCount}
          monthCount={data.monthCount}
          yearCount={data.yearCount}
          allTimeCount={data.allTimeCount}
          color={params.color}
        />

        {/* 4. Full-width 7-bar chart for the current week */}
        <WeekBarGraph
          data={data.weeklyData}
          color={params.color}
        />

        {/* 5. Calendar grid for the current month */}
        <MonthCalendarGraph
          year={now.getFullYear()}
          month={now.getMonth()}
          data={data.monthlyData}
          color={params.color}
        />

        {/* 6. 12-bar year overview */}
        <YearOverviewGraph
          data={data.yearlyData}
          color={params.color}
        />

        {/* 7. All-time completions grouped by weekday — reveals patterns */}
        <DayOfWeekPatternCard
          data={data.dayOfWeekData}
          color={params.color}
        />

        {/* Bottom breathing room above the system home indicator */}
        <View style={styles.bottomPad} />

      </ScrollView>
    </View>
  );
};

// =============================================================================
// STYLES
// =============================================================================

const styles = StyleSheet.create({
  // Fills the full overlay container; background matches the screen bg
  container: {
    flex:            1,
    backgroundColor: '#f5f5f5',
  },

  scroll: {
    flex: 1,
  },

  scrollContent: {
    paddingTop: 16,
  },

  // Space at the bottom so the last card doesn't sit flush against the edge
  bottomPad: {
    height: 40,
  },
});
